services:
  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    volumes:
      - mailpit:/data
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_DATABASE: /data/mailpit.db

  db:
    image: "postgres:latest"
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: journey
      POSTGRES_PASSWORD: 123
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - JOURNEY_DATABASE_NAME=journey
      - JOURNEY_DATABASE_USER=postgres
      - JOURNEY_DATABASE_PASSWORD=123
      - JOURNEY_DATABASE_PORT=5432
      - JOURNEY_DATABASE_HOST=db
    depends_on:
      - db

volumes:
  db:
    driver: local
  mailpit:
    driver: local